In [2]:
include("./src/methods.jl")
using PyPlot, JuMP

In [4]:
c = [0,0,1]
A = [-1. 1. -1.;
     -1. -1. -1.;
     1. 0. 0.
     -1. 0. 0.]
b = [0,0,4.,-1.]

c_simplex, A_simplex, b_simplex,var_relation = simplex_format(c,A,b)

atol = 1e-8
max_iter = 1000
xzero = []
num_const, num_var = size(A)
isempty(xzero) ?  x = zeros(num_var) : x = xzero
if ~all(A*x - b .<= atol)
    phaseI = true
    c_phaseI,A_phaseI,b_phaseI,
        x_phaseI,bfs,nfs = phaseI_simplex_problem(A_simplex,b_simplex)
    x_simplex = SimplexFromBFS(c_phaseI,A_phaseI,
        b_phaseI,x_phaseI,index_bfs=bfs,index_nfs=nfs)
end
var_relation

Dict{Any,Any} with 3 entries:
  2 => [2, 3]
  3 => [4, 5]
  1 => [1]

In [89]:
c = [0,0,1]
A = [-1. 1. -1.;
     -1. -1. -1.;
     1. 0. 0.
     -1. 0. 0.]
b = [0,0,4.,-1.]
A*[4,4,4] .<= b

4-element BitArray{1}:
 1
 1
 1
 1

In [73]:
model = Model(Clp.Optimizer)
@variable(model, x[1:size(c)[1]])
@constraint(model,A*x.<=b) 
@constraint(model,x[4].>=0) 
@objective(model, Min, c'*x)
optimize!(model)


Coin0506I Presolve 0 (-6) rows, 0 (-4) columns and 0 (-11) elements
Clp3002W Empty problem - 0 rows, 0 columns and 0 elements
Clp0000I Optimal - objective value 0
Coin0511I After Postsolve, objective 0, infeasibilities - dual 0 (0), primal 0 (0)
Clp0032I Optimal objective 0 - 0 iterations time 0.002, Presolve 0.00


In [78]:
xo = zeros(size(c)[1])
for i = 1:size(c)[1]
    xo[i] = value(x[1])
end


5-element Array{Float64,1}:
  0.0
  0.0
  4.0
 -1.0
  0.0

In [19]:
c = [0,0,1]
A = [-1. 1. -1.;
     -1. -1. -1.;
     1. 0. 0.
     -1. 0. 0.]
b = [0,0,4.,0.]
cs,As,bs,varsplit = simplex_format(c,A,b)
x = [0.,0,0,0,0,0,0,4]
x_simplex = SimplexFromBFS(cs,As,bs,x,index_bfs=[6,7,8],index_nfs=[1,2,3,4,5])
x_simplex = x_simplex[:,2]
simplex_to_circus = variables_relation(varsplit,3)
x_circus = variable_simplex_to_circus(simplex_to_circus,x_simplex)

3-element Array{Float64,1}:
  4.0
  0.0
 -4.0

In [3]:
x_simplex = variable_circus_to_simplex(simplex_to_circus,x_circus,cs,As,bs)

8-element Array{Float64,1}:
 4.0
 0.0
 0.0
 0.0
 4.0
 0.0
 0.0
 0.0

#### Phase 1


In [4]:
c = [0,0,1]
A = [-1. 1. -1.;
     -1. -1. -1.;
     1. 0. 0.
     -1. 0. 0.]
b = [0,0,4.,-1.]

x = [0,0,0,0,0,0,0,4,1]
cs,As,bs,varsplit = simplex_format(c,A,b)

([0, 0, 0, 1, -1, 0, 0, 0, 0], [-1.0 1.0 … 0.0 0.0; -1.0 -1.0 … 0.0 0.0; 1.0 0.0 … 1.0 0.0; -1.0 0.0 … 0.0 1.0], [0.0; 0.0; 4.0; -1.0], [2, 3])

In [5]:
cpi, Api, bpi, xpi,bfs_pi,nfs_pi = phaseI_simplex_problem(As,bs)

([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0], [-1.0 1.0 … 0.0 0.0; -1.0 -1.0 … 0.0 0.0; 1.0 0.0 … 1.0 0.0; 1.0 -0.0 … 0.0 1.0], [0.0; 0.0; 4.0; 1.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 1.0], [10, 11, 12, 13], [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x_simplex = SimplexFromBFS(cpi,Api,bpi,xpi,index_bfs=bfs_pi,index_nfs=nfs_pi)

x_simplex = x_simplex[1:9,2]

simplex_to_circus = variables_relation(varsplit,3)
x_circus = variable_simplex_to_circus(simplex_to_circus,x_simplex)

3-element Array{Float64,1}:
  1.0
  0.0
 -1.0

In [7]:
c = [0,0,1]
A = [-1. 1. -1.;
     -1. -1. -1.;
     1. 0. 0.
     -1. 0. 0.]
b = [0,0,4.,-1.]
xo = x_circus

pygui(true)
px= [1,4 ,4 ,1 ,1,1,1 ,1,4,4,4 ,4]
py= [0,0 ,-4,-4,0,4,-4,4,4,-4,0,4]
pz= [-1,-4,0 ,3 ,-1,3,3 ,3,0,0,-4,0]
plt= PyPlot.plot3D(px,py,pz)
PyPlot.scatter3D([xo[1]],[xo[2]],[xo[3]])

PyObject <mpl_toolkits.mplot3d.art3d.Path3DCollection object at 0x7f2a0055a790>